### ISSUE TITLE
Add a mail contact

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#11]

**Comment by pierreozoux** [comment]
IAgreeThat@ihavesomethingtohi.de

What do you think?

**Comment by dsalber** [comment]
Doesn't it seem like we're closing the door to people who don't agree? What about just contact@ or hello@ ?

**Comment by pierreozoux** [comment]
`hello@` is fine indeed :)

**Comment by pierreozoux** [comment]
merged with #8
