### ISSUE TITLE
Tools for phone

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#22]
For instance: https://www.torproject.org/docs/android.html.en

**Comment by frju365** [comment]
There is very interesting things which are not concerning tools but the phone itself : 
- the campaign from the FSFE : https://fsfe.org/campaigns/android/android.html
- the Blackphone
- the plasma-mobile project made by KDE
- The purism phone : https://puri.sm/shop/librem-5/

Few idea ...

For Tools  : 
- Orbot
- Silence for the message
- Ring  : https://ring.cx/
- Fdroid
- AndOTP
- DuckDuckGo App
- Nextcloud App
- OsmAnd (Application using the maps from Open Street Map)
- KDE Connect
- Riot.IM


... one more time few idea I have now ;)

**Comment by frju365** [comment]
Many tools... Perhaps if we make two different MD files, one for tools, other for Phone distro, it can be good.

**Comment by frju365** [comment]
Fix in the latest develop branch.
