### ISSUE TITLE
Other search engines suggestions

### ISSUE THREAD

**Issue by Zeriuno** [pierreozoux/ihavesomethingtohi.de#36]
Thank you for this project!

I was thinking that some others search engines could be also suggested (even if perhaps Duckduckgo is the most easy to use).

https://duckduckgo.com/html (with no tracking for the results)
https://ixquick.com (bing proxied)
https://startpage.com (google proxied)
https://searx.me (metasearch engine open source https://github.com/asciimoo/searx)
https://www.tineye.com/ (the only reverse image search engine I know outside of Google)

I don't know how you could suggest those in the context of the website (maybe a "Read more" link?), but I thought it was worth to share the list with others, to spread knowledge and maybe learn something new too!

**Comment by pierreozoux** [comment]
Yes indeed it is nice, thanks!

We'll have to think about a UI for that.

**Comment by Zeriuno** [comment]
Oh, I forgot: another search engine proxy is disconnect, now adopted by
Tor: https://search.disconnect.me/
