### ISSUE TITLE
Prism break

### ISSUE THREAD

**Issue by paultranvan** [pierreozoux/ihavesomethingtohi.de#38]
I just found out https://prism-break.org/en/ 
It gives a great list of projects to escape from mass surveillance and is available in several languages. 
I guess it could be a good source of inspiration, and maybe should be referenced somehow

**Comment by pierreozoux** [comment]
Already on the footer of tools :)
https://github.com/LisbonInternetFreedom/ihavesomethingtohi.de/blob/source/app/_layouts/tools.html#L103

But thanks :)

**Comment by paultranvan** [comment]
Oops, missed that, sorry :)
