### ISSUE TITLE
Other Linux distros to consider

### ISSUE THREAD

**Issue by ruionwriting** [pierreozoux/ihavesomethingtohi.de#39]
I noticed that only Ubuntu is recommended. Maybe is because is the most popular and easy to install? Would be great to see others Debian/Ubuntu derivatives like Mint or Elementary, Arch/Manjaro, etc.

**Comment by pierreozoux** [comment]
Yes, it is one of the common feedback, thank you!

**Comment by frju365** [comment]
Fix in last commit. Ofc : suggestions on the list are welcome.
