### ISSUE TITLE
Did you give up this project ?

### ISSUE THREAD

**Issue by frju365** [pierreozoux/ihavesomethingtohi.de#41]
Hello,
We are in 2018. I'm wondering if you gave up this project or if it's status is dormant ? I want to contribute to it but I don't know if it's good or not ? Perhaps it's time to add collaborators if you don't have much time to update it... :)

Thanks in advance for your answer,

frju365

**Comment by frju365** [comment]
In fact, I would be interesting in taking the project(own if nobody update it) and to host the website too...

**Comment by pierreozoux** [comment]
Hello!

yes, it's been a while we didn't do anything on this project!

Here you are :) You are now collaborator!

Just ping me when you need a new deploy.
If there are more deploys, I'll automate that.

**Comment by frju365** [comment]
Don't worry. I will try to contribute a bit and to update some info like distribution like arkos and cozy which are no longer maintained.

**Comment by frju365** [comment]
Thanks ! :+1:

**Comment by pierreozoux** [comment]
arkos is over? Sad :/

And cozy is not!

**Comment by pierreozoux** [comment]
I'll plan to add the project I started some years ago: https://indie.host ( I never did, what a shame :/ )

**Comment by frju365** [comment]
Yes, in fact, it's the previous version of Cozy which is not maintained. The proprietary of Arkos did a new project which is Skylark : https://github.com/GetSkylark

If you need help I'm motivated ! :smiley:
