### ISSUE TITLE
DDG?!

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#44]
*Feedback from email: *

Moin

Meint Ihr ernsthaft, daß man DDG als SuMa benutzen sollte? Die sitzen
doch in Amiland und wenn die eine Weisung bekommen, dass sie den Key
für die https Verbindung rausrücken sollen, dann muss nur noch der
Provider eine Anordnung kriegen, dass er ausleiten soll und der Schutz
ist hin.

**Comment by frju365** [comment]
I don't really understand what SuMa is ? any idea ?

**Comment by pierreozoux** [comment]
I don't speak german.

**Comment by frju365** [comment]
Yes, but SuMa has no sense for me and I speak German ;)

**Comment by frju365** [comment]
"Pensez-vous vraiment que qqn doit utiliser DDG (sûrement DuckDuckGo) comme SuMa ? Il siège quand même aux USA et  s'ils obtiennent un ordre selon lequel ils devraient donner la clé de chiffrement https, ensuite seul le fournisseur doit obtenir une commande pour qu'elle soit rejetée et la protection est supprimée."

**Comment by frju365** [comment]
C'est la traduction. Mais je ne comprends pas ce que c'est SuMa. Bon, on comprend l'ensemble, je pense.

**Comment by frju365** [comment]
C'est vrai que DuckDuckGo siège maintenant aux États Unis et que la loi oblige entre autre une surveillance obligatoire. Cela ne concerne pas le Https mais le serveur en lui-même (Portes dérobés présentes par exemple).

Ceci dit, la principale fonction de ce moteur de recherche est d'être respectueux de la vie privée de ses utilisateurs.

**Comment by frju365** [comment]
Bon je ferme cette issue. Reopen it for more dicussion.
