### ISSUE TITLE
Fix css Image background

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#5]
Should we find another image at all?

**Comment by pbouda** [comment]
I would try to find one. And we probably need the logo, to put it on top.

**Comment by pierreozoux** [comment]
I open an issue for the logo

**Comment by pbouda** [comment]
If we are OK with the image (license?) we can close this.

**Comment by pierreozoux** [comment]
yop, I don't know the license :/ If somebody is not happy, we'll change it.
