### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by pierreozoux** [pierreozoux/ihavesomethingtohi.de#8]
- [x] toolbox footer as of http://www.frenchtouchweb.com/IHSTH/page2.html
- [x] contributors
- [x] contacts:
  - mail: hello@
  - GitHub link to participate
- [x] add friends sites
  - https://ssd.eff.org/
  - http://jenairienacacher.fr/
- [x] link to FAQ (even the github page, that's fine)

**Comment by pbouda** [comment]
We have "friends" at the end of the toolbox, IMO we can put the links there.

What is the FAQ? Maybe the Github link in the footer is enough?

**Comment by pierreozoux** [comment]
Great, you did awesome job! danke!
